# Generated by Django 6.1.1 on 2026-09-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('grupo_muscular', models.CharField(max_length=255)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
            ],
        ),
    ]
